import { ArrowRight, Check, X } from 'lucide-react'
import { Carousel } from '@/components/carousel/Carousel'
import { PageContainer } from '@/components/layout/PageContainer'
import { Section } from '@/components/layout/Section'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { ResponsiveMedia } from '@/components/ui/ResponsiveMedia'
import { SectionHeader } from '@/components/ui/SectionHeader'
import { architecture, businessLines, clientSolutions, hero, products, thesis, ventureStudio } from '@/content/home'
function Lines({ lines, highlighted=[] }: { lines:string[]; highlighted?:string[] }) { return <>{lines.map((line)=><span key={line} className={`block ${highlighted.includes(line)?'text-white drop-shadow-[0_0_24px_rgba(255,255,255,.26)]':''}`}>{line}</span>)}</> }
export function Hero(){return <header id="hero" className="relative min-h-[calc(100svh-4rem)] overflow-hidden py-16 sm:py-20 lg:py-28"><PageContainer className="relative grid min-h-[620px] items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div className="relative z-10 max-w-xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.3em] text-muted">{hero.eyebrow}</p><h1 className="text-[clamp(4rem,21vw,7.6rem)] font-semibold leading-[0.78] tracking-[-0.085em] text-ink lg:text-[clamp(6rem,9vw,8.6rem)]"><Lines lines={hero.titleLines} highlighted={hero.highlightedLines}/></h1><p className="mt-8 max-w-md text-lg leading-8 text-muted">{hero.description}</p><div className="mt-9 flex w-full max-w-[190px] flex-col gap-3">{hero.actions.map((a)=><Button key={a.label} href={a.href} variant={a.variant} className="w-full">{a.label}{a.icon?<span>{a.icon}</span>:null}</Button>)}</div></div><div className="pointer-events-none relative mx-auto aspect-[4/5] w-full max-w-[420px] lg:max-w-[560px]"><div className="section-glow left-1/2 top-1/2 h-[72%] w-[72%] -translate-x-1/2 -translate-y-1/2 bg-white/20"/><img src={hero.image} alt="" aria-hidden="true" className="relative z-10 h-full w-full object-contain drop-shadow-[0_0_56px_rgba(255,255,255,.12)]"/></div></PageContainer></header>}
export function Thesis(){return <Section id="operating-model"><PageContainer><SectionHeader eyebrow={thesis.eyebrow} title={<Lines lines={thesis.titleLines}/>} description={thesis.description.map((d)=><p key={d}>{d}</p>)}/><div className="mt-12 grid gap-5 lg:grid-cols-[0.9fr_1.1fr_0.9fr]"><Card className="space-y-3">{thesis.inputs.map(([label,Icon,color])=><div key={String(label)} className="flex items-center gap-3 rounded-2xl bg-white/[.04] p-3"><Icon style={{color:String(color)}} size={20}/><span>{String(label)}</span></div>)}</Card><Card className="grid content-center text-center"><div className="mx-auto flex h-32 w-32 items-center justify-center rounded-full border border-white/15 bg-white/[.06] text-2xl font-semibold shadow-card-glow">Saikan OS</div><p className="mt-6 text-muted">One adaptive operating layer for context, memory and execution.</p></Card><Card className="space-y-3">{thesis.outcomes.map(([title,sub,color,Icon])=><div key={String(title)} className="flex items-center gap-3 rounded-2xl bg-white/[.04] p-3"><Icon style={{color:String(color)}} size={20}/><span><b className="block text-sm">{String(title)}</b><span className="text-xs text-muted">{String(sub)}</span></span></div>)}</Card></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{thesis.capabilities.map(([title,desc,color,Icon])=><Card key={String(title)}><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-2xl bg-white/[.06]" style={{color:String(color)}}>{Icon?<Icon size={20}/>:<span>24/7</span>}</div><h3 className="text-xl font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-muted">{String(desc)}</p></Card>)}</div></PageContainer></Section>}
export function Architecture(){return <Section id="architecture"><PageContainer><SectionHeader eyebrow={architecture.eyebrow} title={<Lines lines={architecture.title}/>} description={architecture.description.map((d)=><p key={d}>{d}</p>)}/><div className="mt-12 lg:hidden"><Carousel items={architecture.layers} ariaLabel="Architecture layers" renderItem={(l)=><LayerCard layer={l}/>}/></div><div className="mt-12 hidden gap-5 lg:grid lg:grid-cols-4">{architecture.layers.map((l)=><LayerCard key={l.id} layer={l}/>)}</div></PageContainer></Section>}
function LayerCard({layer}:{layer:typeof architecture.layers[number]}){return <Card className="min-h-[460px]"><span className="text-xs uppercase tracking-[.24em] text-muted">{layer.kicker}</span><ResponsiveMedia src={layer.image} alt="" className="my-5" ratio="aspect-square"/><h3 className="text-2xl font-semibold">{layer.title}</h3><p className="mt-2 text-sm text-muted">{layer.lead}</p><div className="mt-5 flex flex-wrap gap-2">{layer.points.map((p)=><span key={p} className="rounded-full border border-white/10 px-3 py-1 text-xs" style={{color:layer.accent}}>{p}</span>)}</div></Card>}
export function BusinessLines(){return <Section id="business-lines"><PageContainer><SectionHeader eyebrow={businessLines.eyebrow} title={<Lines lines={businessLines.titleLines}/>} description={<p>{businessLines.description}</p>}/><div className="mt-12 grid gap-5 lg:grid-cols-3">{businessLines.items.map((i)=><Card interactive key={i.key}><ResponsiveMedia src={i.asset} alt="" ratio="aspect-[5/4]"/><h3 className="mt-6 text-2xl font-semibold">{i.title}</h3><p className="mt-2 min-h-12 text-muted">{i.body}</p><a href={`#${i.targetId}`} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">{i.cta}<ArrowRight size={16}/></a></Card>)}</div></PageContainer></Section>}
function CompareCard({title,items,negative=false}:{title:string;items:string[];negative?:boolean}){return <Card><h3 className="text-2xl font-semibold">{title}</h3><div className="mt-6 space-y-3">{items.map((i)=><div key={i} className="flex items-center gap-3 rounded-2xl bg-white/[.04] p-3">{negative?<X className="text-pulse" size={18}/>:<Check className="text-brain" size={18}/>}<span>{i}</span></div>)}</div></Card>}
export function ClientSolutions(){return <Section id="client-solutions"><PageContainer><SectionHeader eyebrow={clientSolutions.eyebrow} title={<Lines lines={clientSolutions.titleLines}/>} description={<p>{clientSolutions.description}</p>}/><div className="mt-12 grid gap-5 lg:grid-cols-2"><CompareCard title="Before Saikan" items={clientSolutions.beforeItems} negative/><CompareCard title="After Saikan" items={clientSolutions.afterItems}/></div><div className="mt-5 grid gap-5 md:grid-cols-3">{clientSolutions.steps.map(([n,t,b])=><Card key={String(n)}><span className="text-sm text-muted">{String(n)}</span><h3 className="mt-3 text-xl font-semibold">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-muted">{String(b)}</p></Card>)}</div></PageContainer></Section>}
export function Products(){return <Section id="products"><PageContainer><SectionHeader eyebrow={products.eyebrow} title={<Lines lines={products.titleLines} highlighted={products.highlightedLines}/>} description={<p>{products.description}</p>}/><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{products.items.map(([name,audience,body,logo,accent,points])=><Card key={String(name)} style={{'--accent':String(accent)} as React.CSSProperties}><div className="section-glow right-5 top-5 h-28 w-28 bg-[var(--accent)]/25"/><img src={String(logo)} alt={`${String(name)} logo`} className="relative z-10 h-20 w-20 object-contain"/><p className="mt-5 text-xs uppercase tracking-[.22em] text-muted">{String(audience)}</p><h3 className="mt-2 text-2xl font-semibold">{String(name)}</h3><p className="mt-2 text-sm text-muted">{String(body)}</p><div className="mt-5 flex flex-wrap gap-2">{(points as string[]).map((p)=><span key={p} className="rounded-full border border-white/10 px-3 py-1 text-xs text-muted">{p}</span>)}</div></Card>)}</div></PageContainer></Section>}
export function VentureStudio(){return <Section id="venture-studio"><PageContainer><SectionHeader eyebrow={ventureStudio.eyebrow} title={<Lines lines={ventureStudio.titleLines} highlighted={ventureStudio.highlightedLines}/>} description={<p>{ventureStudio.description}</p>}/><div className="mt-12 grid gap-5 md:grid-cols-3">{ventureStudio.items.map(([name,eyebrow,body,logo,accent])=><Card key={String(name)} style={{'--accent':String(accent)} as React.CSSProperties}><div className="flex h-24 items-center justify-center rounded-3xl bg-white/[.04]"><img src={String(logo)} alt={String(name)} className="max-h-14 object-contain"/></div><p className="mt-5 text-xs uppercase tracking-[.22em] text-muted">{String(eyebrow)}</p><h3 className="mt-2 text-2xl font-semibold">{String(name)}</h3><p className="mt-2 text-sm text-muted">{String(body)}</p></Card>)}</div></PageContainer></Section>}
export function FinalCTA(){return <Section id="final-cta" compact><PageContainer><Card className="text-center"><h2 className="text-4xl font-semibold tracking-[-.05em] md:text-6xl">Build your operating system.</h2><p className="mx-auto mt-5 max-w-2xl text-muted">Bring your operations, knowledge and execution into one adaptive AI layer.</p><Button href="/contact" size="lg" className="mt-8">Book a Call ↗</Button></Card></PageContainer></Section>}
